name: Credit Card Transaction CICD

on:
  push:
    branches:
      - main   # ✅ space required after "-"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r utils/requirements.txt
          pip install pytest pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV   # ✅ use "=" instead of "+"

      - name: Run Pytest with Coverage
        run: pytest --cov=data --cov-report=term --cov-fail-under=80 tests/spark_job_test.py

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}

      # Upload PySpark Job to GCS
      - name: Upload Spark Job to GCS
        run:
          gsutil cp data/spark_job.py gs://avd-buck-credit-card-analysis/spark_job/
          gsutil cp data/load_users_to_bq.py gs://avd-buck-credit-card-analysis/spark_job/

      # Upload Airflow DAG to Composer
      - name: Upload Airflow DAG to Composer
        run: 
          gcloud composewr environments storage dags import \
          --environments airflow  \ 
          --location us-central1 \
          --source airflow/airflow_job.py


      