name: Credit Card Transaction CICD

on:
  push:
    branches:
      - main   # ✅ space required after "-"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r utils/requirements.txt
          pip install pytest pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV   # ✅ use "=" instead of "+"

      - name: Run Pytest with Coverage
        run: pytest --cov=data --cov-report=term --cov-fail-under=80 tests/spark_job_test.py

deploy-to-prod:
  runs-on: ubuntu-latest
  needs: run-tests

  steps:
    - name: Checkout Code
      run: echo "diploy....."